### ISSUE TITLE
Paimon is down. Cannot get short-term dev free token.

### ISSUE THREAD

**Issue by tlkahn** [wechaty/puppet-support#103]
I cannot get WECHATY_PUPPET_SERVICE_TOKEN as described [here](https://wechaty.js.org/docs/puppet-services/#1-free-token-short-term).

**Comment by huan** [comment]
Please refer to the official Paimon documentation at <https://wechaty.js.org/docs/puppet-services/paimon>

**Comment by zpaimon** [comment]
I think you can get a short term token.
